<h1><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif"><strong>BAB 1. KETENTUAN UMUM</strong></span></span></h1>

<ol>
    <li>
        <h1><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Pengantar</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Syarat-syarat dan ketentuan ini, yang merupakan bagian integral dari Perjanjian (selanjutnya</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">disebut sebagai: &ldquo;Perjanjian&rdquo;), menentukan hak, dan ketentuan penting lainnya yang berlaku</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">pada POINCOIN (selanjutnya disebut sebagai: &quot;Perusahaan&quot;), dengan kantor terdaftarnya</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">di Bogor, Jawa Barat pemilik situs web poincoin.k-rbu.com (selanjutnya disebut sebagai: &ldquo;Situs</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Web Poincoin&rdquo;), serta individu terkait (selanjutnya disebut sebagai: &ldquo;Pelanggan&rdquo;) sesuai dengan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Perjanjian ini yang dinyatakan demikian. Perusahaan dan Pelanggan juga dapat disebut secara</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">perseorangan sebagai &ldquo;Pihak&rdquo; dan bersama sebagai &ldquo;Para pihak&rdquo;. Para pihak menyepakati</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">syarat-syarat berikut ini sehubungan dengan penggunaan layanan yang disediakan oleh</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Perusahaan. Berkaitan dengan hal tersebut di atas, Para pihak dengan ini saling menyetujui</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">sebagai berikut:</span></span>
        </h1>
    </li>
    <li>
        <h1><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Definisi</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">2.1. Untuk keperluan Perjanjian ini, istilah-istilah di bawah ini harus memiliki definisi sebagai</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">berikut:</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">2.1.1. &quot;PELANGGAN&quot; berarti orang yang menyelesaikan proses registrasi dan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">menandatangani Perjanjian ini dengan Perusahaan, sesuai dengan syarat-syarat dan ketentuan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">ini, untuk menggunakan layanan tersebut. Pelanggan harus berusia setidaknya 18 (delapan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">belas) tahun, atau usia kedewasaan secara hukum di yurisdiksi yang bersangkutan (jika bukan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">usia 18 (delapan belas) tahun).</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">2.1.2. &quot;LAYANAN&quot; berarti layanan berkekuatan komputasi pada tingkatan staking yang</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">disetujui antara Kedua pihak dan tercantum di dalam Perjanjian ini.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">2.1.3. &quot;MATA UANG DIGITAL&rdquo; berarti Poincoin, Bitcoin, Ethereum, atau aset digital lainnya</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">yang diterima oleh Perusahaan dan digunakan untuk menyelesaikan transaksi, mengendalikan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">pembuatan unit aset digital tambahan, dan melakukan autentikasi transfer melalui metode</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">kriptografik.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">2.1.4. &quot;ID&quot; berarti kombinasi huruf yang dipilih oleh Pelanggan dan disetujui oleh Perusahaan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">untuk tujuan identifikasi Pelanggan dan penggunaan layanan.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">2.1.5. &ldquo;KATA SANDI&quot; berarti kombinasi huruf atau simbol yang dipilih oleh Pelanggan untuk</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">melindungi atau mengonfirmasi ID yang terdaftar sebelumnya.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">2.1.6. &quot;DATA PRIBADI&quot; berarti informasi identifikasi yang berkaitan dengan orang hidup, atau</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">informasi yang dapat digunakan sebagai gabungan dengan informasi lainnya untuk memastikan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">identitas orang tersebut dengan mudah, yang diberikan untuk penggunaan layanan.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">2.2. Definisi persyaratan yang digunakan dalam Perjanjian ini harus sesuai dengan hukum</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">yang bersangkutan, kebijakan privasi, dan kebijakan lainnya, yang ditentukan secara terpisah</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">dari industri Perusahaan, dan istilah yang digunakan secara umum di dalam industri</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Perusahaan kecuali dinyatakan sebaliknya di paragraf 2.1 di atas.</span></span>
        </h1>
    </li>
    <li>
        <h1><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Informasi Perusahaan</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">3.1. Informasi umum Perusahaan adalah sebagai berikut. Nama: Poincoin Trade Indonesia,</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Nomor registrasi :......., Jenis: perseroan terbatas</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">3.2. Perusahaan harus memposting Perjanjian ini di halaman beranda layanan Perusahaan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">atau menggunakan metode lainnya yang serupa, sehingga Pelanggan dapat mengakses dan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">memahami konten ini dengan mudah.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">3.3. Perusahaan dapat mengamendemen Perjanjian ini dari waktu ke waktu, sepanjang</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">amendemen tidak menyebabkan pelanggaran hukum dan peraturan di wilayah di mana kantor</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">pusat Perusahaan bertempat.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">3.4. Pada saat melakukan amendemen terhadap Perjanjian, Perusahaan harus</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">memberitahukan Pelanggan tanggal berlaku perubahan beserta alasannya tujuh (7) hari</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">sebelum pemberlakuan amendemen. Jika ada amandemen yang tidak disetujui Pelanggan,</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Pelanggan harus diberitahukan 30 hari sebelum pemberlakuan amendemen.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">3.5. Perusahaan tidak diperkenankan memberlakukan ketentuan yang diamendemen</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">kepada Pelanggan yang tidak setuju. Apabila hal tersebut terjadi, Perusahaan dan Pelanggan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">dapat menghentikan Perjanjian ini.</span></span>
        </h1>
    </li>
    <li>
        <h1><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Penggunaan dan Tambahan Peraturan</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">4.1. Perusahaan dapat mengatur persyaratan penggunaan secara terpisah untuk setiap</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">layanan dengan persetujuan Pelanggan.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">4.2. Semua hal yang tidak tercantum dalam Perjanjian ini harus diatur oleh hukum yang</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">berkaitan dan praktik komersial yurisdiksi tempat lokasi kantor pusat Perusahaan.</span></span>
        </h1>
    </li>
    <li>
        <h1><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Pemberitahuan</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">5.1. Perusahaan harus menghubungi Pelanggan untuk tujuan pemberitahuan melalui email.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">5.2. Dalam hal pemberitahuan tersebut dimaksudkan untuk sejumlah pelanggan tidak</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">tertentu, Perusahaan dapat memposting pemberitahuan tersebut di dasbor pemberitahuan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">layanan selama setidaknya 7 hari, atau mempostingnya di situs web Poincoin.</span></span>
        </h1>
    </li>
</ol>

<h1><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">BAB 2. Penggunaan Layanan</span></span></h1>

<ol start="6">
    <li>
        <h1><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Kesimpulan Perjanjian.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">6.1. Perjanjian ini harus ditandatangani oleh individu yang ingin menjadi Pelanggan. Saat</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">individu tersebut mengajukan pembelian Layanan pada tingkatan staking seperti yang</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">ditentukan dalam Paket Plannya (sebagaimana dijelaskan di bawah) dan saat Perusahaan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">menerima pengajuan tersebut, individu menjadi Pelanggan, dan akun Pelanggan dibuat dan,</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">dengan demikian, didaftarkan kepada mereka.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">6.2. Prinsipnya, Perusahaan harus menyetujui pengajuan jika pemohon mengirimkannya</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">sesuai dengan paragraf 6.1 di atas. Namun, Perusahaan dapat menolak pengajuan dan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">menghentikan perjanjian ini jika terjadi kasus berikut:</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">6.2.1. pemohon mengajukan registrasi menggunakan nama palsu atau samaran, atau nama</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">orang lain;</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">6.2.2. pemohon memberikan informasi palsu atau tidak akurat sehubungan dengan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">pengajuan.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">6.2.3. pemohon mengajukan untuk layanan demi tujuan komersial yang ilegal atau terpisah.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">6.3. Perusahaan dapat meminta pemohon memberikan informasi pribadi selama proses</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">pengajuan untuk identifikasi mereka atau tujuan lainnya, yang mana proses pengajuan tidak</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">akan diselesaikan hingga informasi tersebut diberikan.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">6.4. Perusahaan dapat menolak pengajuan registrasi jika fasilitas penambangan digunakan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">dalam kapasitas penuh. Dalam kasus tersebut, Perusahaan harus menyelesaikan masalah</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">sebaik mungkin dan memulai layanan.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">6.5. Dalam hal pengajuan ditolak, Perusahaan harus memberitahukan keputusan tersebut</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">kepada pemohon.</span></span>
        </h1>
    </li>
    <li>
        <h1><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Perubahan Informasi Pelanggan</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Pelanggan dapat mengakses informasi penggunanya yang diberikan untuk tujuan Layanan.</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Pelanggan tidak dapat mengubah atau memodifikasi informasi pengguna yang dianggap perlu</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">untuk manajemen layanan Perusahaan tanpa persetujuan Perusahaan terlebih dahulu.</span></span>
        </h1>
    </li>
    <li>
        <h1><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Layanan yang Disediakan kepada Pelanggan</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">8.1. Perusahaan akan menyediakan Pelanggan dengan kekuatan komputasional pada</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">tingkatan staking yang dispesifikasikan di dalam paket yang diatur di bawah (&ldquo;Paket</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Pertambangan&rdquo;). Layanan harus disediakan menurut upaya terbaik Perusahaan. Meskipun</span></span><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">demikian, Perusahaan harus membuat upaya yang wajar untuk memastikan kesesuaian semua</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">fasilitas dan suplai untuk menyediakan Layanan yang dikelola dengan baik guna menghindari</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">keragaman apa pun, dengan penerapan ketekunan yang sama terhadap urusannya sendiri.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">8.2. Pelanggan memahami risiko yang berkaitan dengan teknologi blockchain dan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">memahami bahwa keragaman dapat terjadi dalam hal protokol yang digunakan untuk</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">melakukan verifikasi transaksi blockchain (&ldquo;penambangan&rdquo;) untuk mata uang kripto</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">menggunakan algoritme yang dipilih oleh Pelanggan.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">8.3. Paket kompensasi diperinci secara terpisah di dasbor Pelanggan di Situs Web</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Poincoin.online.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">8.4. Pelanggan berhak untuk menerima alokasi aset digital harian yang diproduksi dari Paket</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Penambangan.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">8.5. Jumlah aset digital yang dibuat oleh Paket Penambangan berkaitan dengan tingkatan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">staking yang ditentukan di dalamnya.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">8.6. Pelanggan dapat mengelola dan mengendalikan aset digital yang didistribusikan ke Akun</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">miliknya.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">8.6.1. Pelanggan bertanggung jawab atas alokasi tingkatan staking yang dibeli di bawah</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Perjanjian ini.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">8.6.2. Pelanggan dapat memutuskan untuk menambang mata uang kripto selain yang</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">diindikasikan dalam Paket Penambangan, dengan ketentuan Perusahaan akan menyediakan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">untuk pilihan ini.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">8.6.3. Pelanggan memahami bahwa Perusahaan tidak bertanggung jawab atas pemilihan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">atau pewaktuan penambangan mata uang kripto di bawah Perjanjian ini serta protokol yang</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">dipilih untuk penggunaan yang berhubungan dengan Layanan.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">8.6.4. Pelanggan harus memantau dan mengalokasikan tingkatan staking melalui Dasbor.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">8.7. Layanan yang disediakan oleh Perusahaan tidak mengatur keamanan atau jenis</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">investasi apa pun, dan Pelanggan tidak dapat mengharapkan pendapatan, keuntungan, atau</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">yang disebut ROI layanan berkekuatan komputasional apa pun yang disediakan oleh&nbsp;</span></span><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Perusahaan. Perusahaan hanya menyediakan Layanan yang dijelaskan dalam paragraf</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">8.1. dan tidak menjamin keuntungan, pendapatan, atau pemasukan kepada Pelanggan.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">8.8. Pelanggan memahami dan menyetujui bahwa Perusahaan tidak dapat bertanggung</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">jawab atas hadiah staking apa pun, maupun menjamin pengembalian atau penukaran nilai mata</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">uang kripto apa pun yang ditawarkan untuk ditambang. Pelanggan juga memahami dan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">menyetujui bahwa Pelanggan tidak dapat mengklaim apa pun terhadap Perusahaan, kecuali</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">untuk tujuan yang disediakan dengan Layanan yang dibeli oleh Pelanggan.</span></span>
        </h1>
    </li>
    <li>
        <h1><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Batasan Penggunaan Layanan</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">9.1. Perusahaan dapat membatasi penggunaan Layanan Pelanggan jika Perusahaan secara</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">objektif memastikan bahwa Pelanggan mendistribusikan operasi normal layanan Perusahaan,</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">termasuk saat Pelanggan melanggar ketentuan bagian ini atau kasus berikut:</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">9.1.1. Pelanggan gagal memasukkan kata sandi dengan benar lebih dari lima kali berturut-turut;</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">9.1.2. Pelanggan terlibat dalam pembobolan atau penipuan, atau eksploitasi Situs Web</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Poincoin.online dan Layanannya;</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">9.1.3. diduga melakukan penggunaankredensial individu lain secara ilegal</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">9.1.4. Jika perlu, sesuai dengan kebijakan operasional Perusahaan, membatasi kemampuan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Pelanggan untuk masuk.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">9.2. Sesuai kebijakan kebijakan operasional Perusahaan, Perusahaan dapat membatasi</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">atau menunda penggunaan deposit Pelanggan dan layanan penarikan setelah ditemukannya</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">transaksi abnormal yang berkaitan dengan Akun Pelanggan atau alasan yang mirip.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">9.3. Perusahaan dapat langsung mengakhiri Perjanjian atas penggunaan Layanan jika</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Pelanggan melakukan tindakan berikut: pencurian identitas, pembayaran yang curang, phishing</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">suara, penyediaan dan pengoperasian program ilegal, komunikasi ilegal, pembobolan, distribusi</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">kode berbahaya, akses tidak sah.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">9.4. Pelanggan dapat membantah pembatasan yang ditetapkan kepada Pelanggan melalui</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">prosedur yang disediakan Perusahaan. Jika Perusahaan memastikan bahwa pembantahan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Pelanggan dapat dibenarkan, Perusahaan harus segera mencabut pembatasan dan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">melanjutkan penyediaan Layanan.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">9.5. Anak di bawah umur tidak diizinkan untuk mendaftar di Situs Web Poincoin.online,</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">menggunakan atau membeli Layanan yang ditawarkan melalui situs web.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">9.6. Layanan yang ditawarkan via Website Poincoin.online tidak tersedia bagi warga diluar</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Indonesia, Kanada, Cina Tiongkok, Siprus, Kazakistan, Filipina, Polandia, Rusia, Spanyol,</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Amerika Serikat, Ukraina, dan beberapa negara lain dimana apra warga dilarang untuk</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">melakukan persetujuan, mendaftarkan diri di Website Poincoin.online, atau menggunakan atau</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">membeli Layanan melalui website Poincoin.online.</span></span>
        </h1>
    </li>
    <li>
        <h1><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Masa Layanan</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Masa layanan berakhir setelah masa penambangan yang disepakati dan masa penangguhan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">yang diperpanjang.</span></span>
        </h1>
    </li>
    <li>
        <h1><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Penangguhan Layanan</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">11.1. Perusahaan dapat menangguhkan kententuan Layanan sementara tanpa pemberitahuan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">sebelumnya karena alasan penting, seperti pemeriksaan, perluasan, atau penggantian sistem</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">darurat.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">11.2. Jika terjadi penangguhan, Perusahaan harus memberitahukan pelanggan mengenai</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">penangguhan tersebut sebelumnya, atau setelahnya melalui email atau dengan memposting</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">yang berisi pemberitahuan mengenai situs web Perusahaan. Perusahaan dapat menangguhkan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">ketentuan Layanan dalam kasus berikut:</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">11.2.1. saat peralatan dan sistem harus ditingkatkan, diganti, diperiksa, dirawat, diperbaiki</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">11.2.2. saat terjadi kegagalan pada sirkuit khusus</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">11.2.3. saat terjadi kegagalan atau penghentian mekanis karena bencana alam atau keadaan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">darurat nasional;</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">11.2.4. saat ketentuan layanan dibatasi atau ditangguhkan sesuai dengan ketertiban</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">administrasi atau bisnis negara, lembaga pemerintah, lembaga penegak hukum, atau</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">pengadilan yang berwenang.</span></span>
        </h1>
    </li>
    <li>
        <h1><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Ketentuan Periklanan dan Informasi Lainnya</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Perusahaan dapat menyediakan informasi yang berkaitan dengan penggunaan Layanan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">kepada Pelanggan. Pelanggan dapat memilih untuk tidak menerima email, SMS, atau alat</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">komunikasi lainnya yang disediakan oleh Perusahaan sesuai dengan hukum dan peraturan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">yang berlaku.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">12.1. Perusahaan dapat memberikan periklanan atau informasi lainnya kepada Pelanggan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">melalui Situs Web Poincoin.online, di dalam dasbor Pelanggan, atau melalui SMS. Pelanggan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">dapat menolak untuk menerima email, SMS, atau alat komunikasi lainnya yang berisi iklan.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">12.2. Bahkan setelah penambangan dimulai dan penarikan tersedia, Perusahaan dapat</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">meminta informasi pengguna lainnya untuk mematuhi regulasi prosedur verifikasi pelanggan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">(Customer Verification Procedures/KYC) dan anti pencucian uang (Anti-Money&nbsp;</span></span><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Laundering/AML).</span></span>
        </h1>
    </li>
</ol>

<h1><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">BAB 3. Hak dan Kewajiban</span></span></h1>

<ol start="13">
    <li>
        <h1><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Hak dan Kewajiban Perusahaan</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">13.1. Perusahaan memiliki (atau menyewa) semua peralatan dan aset yang digunakan untuk</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">menyediakan layanan. Pelanggan menyetujui bahwa Perusahaan harus mempertahankan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">kepemilikan tunggal dan secara langsung atau tidak langsung mengendalikan dan merawat</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">semua peralatan penambangan aset digital yang digunakan untuk memfasilitasi ketentuan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">layanan penambangan di bawah Paket Penambangan yang relevan.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">13.2. Perusahaan dapat menggunakan pendanaan yang dibayarkan oleh Pelanggan untuk</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">paket penambangan sebagai berikut:</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">13.2.1. 63% untuk memperoleh dan meluncurkan peralatan penambangan digital tambahan,</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">serta untuk pengeluaran lainnya yang berkaitan dengan aktivitas ini.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">13.2.2. 35% untuk menanggung komisi Pelanggan sesuai dengan paket kompensasi yang</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">ditentukan dalam dasbor Pelanggan.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">13.2.3. 2% untuk pengeluaran umum dan administratif untuk memenuhi Perjanjian ini.</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Nilai yang dijelaskan di atas dapat beragam, bergantung pada berbagai faktor di luar kendali</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Perusahaan, yang, tidak akan memengaruhi pelaksanaan Perjanjian ini.</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Rasio pemanfaatan setiap item dapat disesuaikan menurut kebijakan Perusahaan. Jika terjadi</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">penyesuaian atau perubahan, Pelanggan harus diberitahukan setidaknya 30 hari sebelumnya.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">13.3. Jika layanan berkelanjutan tidak dapat diberikan selama masa yang disetujui tanpa</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">alasan yang wajar dan sah, yang di luar kendali Perusahaan, Pelanggan harus diberitahukan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">sebelumnya dan kerugian untuk sisa masa yang disetujui harus digantikan. Metode kompensasi</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">dan perhitungan harus berdasarkan kriteria yang ditetapkan secara terpisah.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">13.4. Perusahaan harus memberikan upaya terbaiknya untuk melindungi data pribadi</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Pelanggan (termasuk informasi kredit) sehingga Pelanggan dapat menggunakan Layanan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">dengan aman, serta harus mematuhi kebijakan privasi.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">13.5. Untuk mencegah gangguan saat Pelanggan menggunakan Layanan, Perusahaan harus</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">melakukan yang terbaik untuk mengembangkan dan merawat personel dan sistem pentingnya.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">13.6. Perusahaan berhak untuk menghentikan koneksi mesin penambangan dan dengan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">demikian, membayar hadiah penambangan sebagai penalti, yang lebih ekonomis dan lebih</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">efisien, serta memungkinkan Perusahaan membayarkan penalti dengan jumlah yang sama</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">dengan hadiah penambangan yang semestinya diterima Pelanggan jika mesin terhubung.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">13.7. Pelanggan memahami bahwa Perusahaan berhak untuk memindahkan penambangan di</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">berbagai mata uang kripto, misalnya, dari Poincoin ke BTC dan dari BTC ke Poincoin jika terjadi</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">kesulitan untuk melikuidasi hadiah penambangan dan membayar listrik serta biaya hosting.</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Namun, Pelanggan berhak untuk menolak perubahan tersebut dengan menghubungi</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Perusahaan melalui email.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">13.8. Perusahaan berhak menangguhkan atau memblokir Akun Pelanggan dan menangguhkan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">semua Layanan yang disediakan kepada Pelanggan jika Pelanggan melanggar ketentuan apa</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">pun dari Perjanjian ini, khususnya kewajiban Pelanggan sebagaimana yang dimaksud dalam</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">paragraf 14.2.</span></span>&nbsp;<br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">13.9. Pelanggan setuju bahwa pengiriman mesin penambangan yang ditentukan dalam Paket</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Penambangan yang dibeli dapat memerlukan waktu hingga 365 hari. Pelanggan juga setuju</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">bahwa hingga mesin penambangan tertentu disediakan, Pelanggan harus menerima hadiah</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">penambangan dalam jumlah yang sama dengan yang akan diperoleh jika mesin penambangan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">telah terhubung dan beroperasi.</span></span>
        </h1>
    </li>
    <li>
        <h1><span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Kewajiban Pelanggan</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">14.1. Pelanggan tidak dapat terlibat atau melakukan hal-hal berikut sehubungan dengan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">penggunaan situs web dan Layanan:</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">14.1.1. Memberikan data palsu saat mendaftar atau mengubah data pribadi.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">14.1.2. Menggunakan data pribadi, kata sandi, ID anggota lain.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">14.1.3. Mengubah informasi yang diterbitkan Perusahaan mengenai Layanan tanpa persetujuan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">sebelumnya dari Perusahaan.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">14.1.4. Melanggar hak kekayaan intelektual Perusahaan atau hak lainnya.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">14.1.5. Menggunakan VPN untuk mengatasi pembatasan situs.</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">14.2. Saat menggunakan Layanan, Pelanggan juga setuju bahwa Pelanggan tidak dapat:</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">14.2.1. menghalangi akses ke atau penggunaan situs web untuk Pelanggan lain;</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">14.2.2. merusak reputasi Perusahaan atau membuat pernyataan atau perwakilan palsu atau</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">menyesatkan tentang Perusahaan;</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">14.2.3. membuat lebih dari satu Akun untuk akses ke Layanan;</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">14.2.4. mengubah, menutupi, atau menyembunyikan alamat IP Pelanggan atau detail lainnya</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">untuk mengakses Layanan;</span></span><br />
            <span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">14.2.5. PERHATIAN Pertambangan aset kripto merupakan aktivitas beresiko tinggi.</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">Pendapatan aset kripto sangat fluktuatif, dimana pendapatan dapat berubah secara signifikan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">dari waktu ke waktu. Harap menggunakan pertimbangan ekstra dalam membuat keputusan</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">untuk membeli paket atau menjual aset kripto. bioner tidak memaksa pengguna untuk membeli</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">aset kripto, sebagai investasi, atau aksi mencari keuntungan. Semua keputusan pelanggan aset</span></span>&nbsp;<span style="font-size:14px"><span style="font-family:Arial,Helvetica,sans-serif">kripto merupakan keputusan independen oleh pengguna.</span></span>
        </h1>
    </li>
</ol>